#
# This file contains configuration flags to customize your site
#

# Site details (displayed in the header)
author: Ekstrapoint
name: Ekstrapoint Blog
title: Ekstrapoint Blog
description: Ekstrapoint is a gamified loyalty platform offering users the opportunity to earn points by engaging with online casinos. These points can be redeemed for real rewards, enhancing the online gaming experience.
keywords: "casino bonus, no deposit bonus, free spins, online casino reviews, Ekstrapoint, free to play, free slot tournaments, free slots tournaments, slot competitions, online slot tournaments, free-to-play slot tournaments, slot tournament leaderboard, daily slot tournaments, weekly slot tournaments, monthly slot tournaments, no deposit slot tournament, live slot tournaments, social slot tournaments, free spins tournaments, slot duels competition, leaderboard slot challenge, free slot tournaments win real money, daily free spins tournament, multiplayer slot duels online, free casino slot competitions no entry fee, mobile slot tournaments free play, free slot leaderboard races"
logo: images/logo.svg

# Language of the website
locale: en-US

# Company details
company:
  analytics:
    google_id: 
    google_ads_id: 
    microsoft_clarity_id: 
  cta:
    text: "Play Free Competition"
    url: "https://ekstrapoint.com/competitions/"
  socials:
    youtube: 
    instagram: 
    facebook: 
    tiktok: 
    x: 
    linkedin: 
    pinterest: 
    telegram: 
    discord: 
    github: 
    email: 
    phone: 
  icon_size: "24"
  colors:
    main:
      background: "#fff"
      foreground: "#1a2433"
    body:
      background: "#fff"
      foreground: "#1a2433"
    accent: "#3765dd"
  fonts:
    google:
      - "Roboto:ital,wght@0,100..900;1,100..900"
    heading: "'Roboto'"
    body: "'Roboto'"

# Navigation items
navigation:
  header:
    - title: "About Us"
      url: "/about-us"
    - title: "Contact Us"
      url: "/contact-us"
    - title: "Competitions"
      url: "/competitions"
    - title: "How It Works"
      url: "/how-it-works"
    - title: "Shop"
      url: "/shop"
    - title: "Casino Bonuses"
      url: "/casino-bonuses"
    - title: "Top Casinos"
      url: "/casinos/top-casinos"
  footer:
    - title: "Terms and Conditions"
      url: "/terms-and-conditions"
    - title: "Privacy Policy"
      url: "/privacy-policy"
    - title: "Cookie Policy"
      url: "/cookie-policy"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://blog.ekstrapoint.com

# Paginate after X amount of posts
paginate: 10

#
# NOTHING TO CHANGE BEYOND THIS POINT
#

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# ONLY NECESSARY ON SUB-PAGE / GITHUB-BASED HOSTING
baseurl: 

# Theme used as a base
theme: jekyll-swiss

# Slug of paginated page
paginate_path: "/page/:num"

# Exclude pagination pages by default in sitemap
defaults:
  - scope:
      path: "page"
    values:
      sitemap: false

# Permalink slug (DO NOT TOUCH)
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Disable Github Metadata plugin
github: [metadata]

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap
  - jekyll-feed # Create an Atom RSS feed
  - jekyll-paginate # Support pagination of posts

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - __init/
  - init_mac.command
  - init_windows.bat